name: minha_casa_rpg_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.1.0
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1


flutter:
  uses-material-design: true
  generate: true

  assets:
     - assets/images/
     - assets/icons/
     - assets/texture/
     - assets/images/avatar/

  fonts:
  
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel/static/Cinzel-Bold.ttf

    - family: Cinzel_Decorative
      fonts:
        - asset: assets/fonts/Cinzel_Decorative/CinzelDecorative-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cinzel_Decorative/CinzelDecorative-Bold.ttf
          weight: 700

