spring:
  application:
    name: RepublicaQuestAPI
  datasource:
    url: jdbc:postgresql://localhost:5432/repquest
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true